# Generated by Django 4.2.2 on 2023-06-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('week', 'Week'), ('all_time', 'All Time')], default='day', max_length=8)),
                ('speed', models.FloatField()),
                ('quality', models.FloatField()),
                ('benevolence', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_user_id', to='product.user')),
            ],
            options={
                'db_table': 'rates_history',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('benevolence', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assessed_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessed_user_id', to='product.user')),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_user_id', to='product.user')),
            ],
            options={
                'db_table': 'rates',
            },
        ),
    ]
